name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy to Production
        if: success()
        run: |
          echo "Deploying to production..."
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} ./build/* user@${{ secrets.DEPLOYMENT_SERVER_IP }}:/path/to/deploy/
